---
spec/spec_helper.rb:
  mock_with: ":rspec"
  coverage_report: true
spec/default_facts.yml:
  extra_facts:
    common_appdata: 'C:/ProgramData'
.rubocop.yml:
  default_configs:
    "Layout/BlockAlignment":
       Enabled: False
