name: Call main PR testing workflows

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'examples/**'
      - 'CODEOWNERS'
      - 'LICENSE'

jobs:
  spec_testing:
    name: "Spec testing"
    uses: ./.github/workflows/spec.yml
